### ISSUE TITLE
Why need use array to wrap runComputed?

### ISSUE THREAD

**Issue by yolio2003** [jbreckmckye/trkl#10]
I noticed that the computationToken is wrapped as array `[runComputed]`, i didn't understand the intent of this usage, just want to ask why. thx.

**Comment by jbreckmckye** [comment]
It's a long time since I wrote this, about six years or so. I'm not sure, actually.

My first thought was that I must have been trying to give the `computationToken` a unique struct to identify it for `detectCircularity`, but given that the `runComputed` is an inline function I don't think it's needed. Maybe I intended to add some other 'metadata' to a tuple? It's been so long

Anyway, I reckon we can get rid of it, shave off >2 bytes.

**Comment by yolio2003** [comment]
thank you very much!
